### ISSUE TITLE
SunEditor: Inherit Font From PF Theme

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1140]
Must use PF theme font and not SunEditor default font.

```css
/* Use PF theme font */
body .sun-editor,
body .sun-editor-editable {
  font-family: var(--font-family);
}
```
