### ISSUE TITLE
Orgchart: Version Update (to 5.0.0)

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions#1182]
We updated orgchart to the latest v2 in this ticket: https://github.com/primefaces-extensions/primefaces-extensions/issues/1017

However, it was discovered that font awesome icons were no longer working after the upgrade (https://github.com/primefaces-extensions/primefaces-extensions/issues/1050). I applied the workaround to apply default icons (https://github.com/jxmai/primefaces-extensions/commit/c1a84abfbb43c74f8a67139a6012d364a8f9eeec). 

Most recently, we were notified by orgchart maintainer that the issue was addressed in v3.7.0, so we have to upgrade orgchart to the same version before we can properly address the icon issues.

**Comment by jxmai** [comment]
Note: after we update the orgchart lib to the latest version: v3.8.0, https://github.com/jxmai/primefaces-extensions/commit/f3c44af3983522ffa2dae7171fbcee11778a873c, the orgchart layout is mis-aligned. Previously I have discovered the same issue in v3 so that I migrated the orgchart version up to v2 only.

- To isolate the issue, I put the orgchart.js and orchart.css into a separate pure HTML, Javascript test project and see if they have the same problem.  Screenshot and comment are posted under a commit: https://github.com/jxmai/orgchart_testing/commit/ff0968daf41eb9722a65d3bf60351023d571bf52#commitcomment-120372388. Interestingly, this issue only happens in our JSF integration but not in the test project.

- To isolate the issue further in case it is JQuery issue, I load the exact Jquery version from PF https://github.com/jxmai/orgchart_testing/commit/e2862a180e829a3a9ac165d46055a9f51f67fb91, but the same issue occur in the local showcase.

- To isolate the potential if there's any incorrect API call in the new version from PFE JS options, I hardcode the orgchart invocation in PFE show case using from orgchart demo. However, the following demo works in the test project but not in our showcase.

```js
var datascource = {
	      'name': 'Lao Lao',
	      'title': 'general manager',
	      'children': [
	        { 'name': 'Bo Miao', 'title': 'department manager' },
	        { 'name': 'Su Miao', 'title': 'department manager',
	          'children': [
	            { 'name': 'Tie Hua', 'title': 'senior engineer' },
	            { 'name': 'Hei Hei', 'title': 'senior engineer',
	              'children': [
	                { 'name': 'Pang Pang', 'title': 'engineer' },
	                { 'name': 'Dan Dan', 'title': 'UE engineer' ,
	                'children': [
	                  { 'name': 'Er Dan', 'title': 'engineer' },
	                  { 'name': 'San Dan', 'title': 'engineer',
	                    'children': [
	                      { 'name': 'Si Dan', 'title': 'intern' },
	                      { 'name': 'Wu Dan', 'title': 'intern' }
	                    ]
	                  }
	                ]}
	              ]
	            }
	          ]
	        },
	        { 'name': 'Hong Miao', 'title': 'department manager' },
	        { 'name': 'Chun Miao', 'title': 'department manager',
	          'children': [
	            { 'name': 'Bing Qin', 'title': 'senior engineer' },
	            { 'name': 'Yue Yue', 'title': 'senior engineer',
	              'children': [
	                { 'name': 'Er Yue', 'title': 'engineer' },
	                { 'name': 'San Yue', 'title': 'UE engineer' }
	              ]
	            }
	          ]
	        }
	      ]
	    };
        
        
        //opts['data'] = JSON.parse(opts['data'])
        opts['data'] = datascource

        // this.orgchart = this.jq.orgchart(opts);
        this.orgchart = this.jq.orgchart({
	      'data' : datascource,
	      'nodeContent': 'title',
	    });
```

I isolate the commit from orgchart that causes the behavior differences: https://github.com/dabeng/OrgChart/commit/8c5427e74e6dde7b27b75a10fb803b62d6db067a. However, the question still remains about why it only causes issue in our JSF integration but not on the demo. The orgchart commit is relative large and it is not immediately obvious about the impact as many files have been changed.

**Comment by melloware** [comment]
I wonder if it is the order the CSS is loaded is different?

**Comment by jxmai** [comment]
That's a good idea. Thanks for the hints. 

I compared the CSS being used by showcase vs the one used by the demo app from orgchart

```css
showcase:

/*! CSS Used from: http://localhost:8090/showcase-ext/javax.faces.resource/theme.css.jsf?ln=primefaces-arya&v=13.0.0-RC2&e=13.0.0-SNAPSHOT */
*{box-sizing:border-box;}
/*! CSS Used from: http://localhost:8090/showcase-ext/javax.faces.resource/orgchart/orgchart.css.jsf?ln=primefaces-extensions&v=13.0.0-RC2&e=13.0.0-SNAPSHOT */
.orgchart .node:not(:only-child)::after{content:"";position:absolute;bottom:-11px;left:calc(50% - 1px);width:2px;height:9px;background-color:rgba(217, 83, 79, 0.8);}
.orgchart ul li .node:hover{background-color:rgba(238, 217, 54, 0.5);}
.orgchart .node{box-sizing:border-box;display:inline-block;position:relative;margin:0 0 20px 0;padding:3px;border:2px dashed transparent;text-align:center;}
.orgchart .node:hover{background-color:rgba(238, 217, 54, 0.5);transition:.5s;cursor:default;z-index:20;}
.orgchart .node .title{box-sizing:border-box;padding:2px;width:130px;text-align:center;font-size:0.75rem;font-weight:bold;height:20px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;background-color:rgba(217, 83, 79, 0.8);color:#fff;border-radius:4px 4px 0 0;}
.orgchart .node .content{box-sizing:border-box;padding:2px;height:20px;font-size:0.625rem;border:1px solid rgba(217, 83, 79, 0.8);border-radius:0 0 4px 4px;text-align:center;background-color:#fff;color:#333;text-overflow:ellipsis;white-space:nowrap;}
.orgchart .node .edge{position:absolute;cursor:default;transition:.2s;}
.orgchart .node .edge::before{border-color:rgba(68, 157, 68, 0.5);}
.orgchart .node .edge:hover{cursor:pointer;}
.orgchart .edge:hover::before{border-color:#449d44;}
.orgchart .node .verticalEdge{width:calc(100% - 6px);width:-webkit-calc(100% - 6px);width:-moz-calc(100% - 6px);height:10px;left:3px;}
.orgchart .node .verticalEdge::before{position:absolute;left:calc(50% - 0.3125rem);}
.orgchart .node .bottomEdge{bottom:-2px;}
.orgchart .node{transition:transform 0.3s, opacity 0.3s;}
.oci{display:inline-block;position:relative;font-style:normal;font-family:Arial;}
/*! CSS Used from: http://localhost:8090/showcase-ext/javax.faces.resource/global.css.jsf?ln=css */
*{font-size:12px;}


demo

/*! CSS Used from: http://localhost:8080/orchart_testing/css/jquery.orgchart.css */
.orgchart .node:not(:only-child)::after{content:"";position:absolute;bottom:-12px;left:calc(50% - 1px);width:2px;height:10px;background-color:rgba(217, 83, 79, 0.8);}
.orgchart ul li .node:hover{background-color:rgba(238, 217, 54, 0.5);}
.orgchart .node{box-sizing:border-box;display:inline-block;position:relative;margin:0 0 20px 0;padding:3px;border:2px dashed transparent;text-align:center;}
.orgchart .node:hover{background-color:rgba(238, 217, 54, 0.5);transition:.5s;cursor:default;z-index:20;}
.orgchart .node .title{box-sizing:border-box;width:130px;text-align:center;font-size:12px;font-weight:bold;height:20px;line-height:20px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;background-color:rgba(217, 83, 79, 0.8);color:#fff;border-radius:4px 4px 0 0;}
.orgchart .node .title .parentNodeSymbol{float:left;}
.orgchart .node .title .parentNodeSymbol::before{color:#fff;}
.orgchart .node .title .parentNodeSymbol::after{background-color:#fff;}
.orgchart .node .content{box-sizing:border-box;width:130px;height:20px;line-height:20px;font-size:10px;border:1px solid rgba(217, 83, 79, 0.8);border-width:0 1px 1px 1px;border-radius:0 0 0.25rem 0.25rem;text-align:center;background-color:#fff;color:#333;text-overflow:ellipsis;white-space:nowrap;}
.orgchart .node .edge{position:absolute;cursor:default;transition:.2s;}
.orgchart .node .edge::before{border-color:rgba(68, 157, 68, 0.5);}
.orgchart .node .edge:hover{cursor:pointer;}
.orgchart .edge:hover::before{border-color:#449d44;}
.orgchart .node .verticalEdge{width:calc(100% - 6px);height:10px;left:3px;}
.orgchart .node .verticalEdge::before{position:absolute;left:calc(50% - 5px);}
.orgchart .node .bottomEdge{bottom:-2px;}
.orgchart .node{transition:transform 0.3s, opacity 0.3s;}
.oci{display:inline-block;position:relative;font-style:normal;font-family:Arial;}
.oci-menu::before{content:"â‰¡";display:inline-block;width:1rem;height:1rem;text-align:center;line-height:1rem;color:#000;font-size:1rem;}
```


I can only spot the extra `*{box-sizing:border-box;}` so that I went ahead to apply the same css in the demo app and see if that's the issue, and it isn't.


https://github.com/jxmai/orgchart_testing/commit/da492df4eeec1a916e67b0a9da601a7ec43f2ea1


---

The effort isn't wasted however, since while I was checking the CSS load order, I discovered an **important detail**.

https://github.com/dabeng/OrgChart/commit/8c5427e74e6dde7b27b75a10fb803b62d6db067a#diff-3c27afa5de1c62016dceb22b5c538f347eb638664109c31024d3b17caef2c590

![Screen Shot 2023-07-02 at 2 57 24 PM](https://github.com/primefaces-extensions/primefaces-extensions/assets/10467831/3e457658-fef3-4c84-a1b0-5484a273b74d)

without this CSS, the demo app would mis-align as well. In this case, I may already know what to do to fix this issue in our integration.
