### ISSUE TITLE
SunEditor: Dialog and positioning fixes

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#1235]
As discussed on Discord when adding an image the position is off because of..

```css
/* Ensure the editor can receive input in dialog */
body .sun-editor .se-wrapper .se-wrapper-inner {
  position:relative;
  z-index: 9999;
}
```

**Comment by melloware** [comment]
Submitted fix but re-opening so it can be tested by others.

**Comment by melloware** [comment]
final fix:

```css
.sun-editor .se-wrapper {
   z-index: 9999 !important;
}
```
