### ISSUE TITLE
PrimeIcons: add CSS class to body indicating they're loaded and patch theme

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#126]
See https://github.com/primefaces-extensions/core/commit/1b046f47f60bcd41b7154dfeffc81ceb6c397af2#r35403172

**Comment by melloware** [comment]
Also i got the feeling from the PrimeFaces 10 roadmap that all themes are going to be updated for PrimeIcons including all Premium themes.

**Comment by melloware** [comment]
I added Saga, Vela, and Arya the new PrimeOne themes to our JS method.
```javascript
    isPrimeIconTheme: function (theme) {
        var theme = PrimeFacesExt.getTheme();
        switch (theme) {
            case "nova-light":
            case "nova-dark":
            case "nova-colored":
            case "luna-blue":
            case "luna-amber":
            case "luna-green":
            case "luna-pink":
            case "saga":
            case "vela":
            case "arya":
                return true;
            default:
                return false;
        }
        ;
    },
```

**Comment by melloware** [comment]
Also I stand corrected the new Saga theme is the default theme not Nova Light for PF10.

**Comment by melloware** [comment]
@jepsar as of PF 10 PF always includes PrimeIcons no matter what.  So I am wondering if we should clean this up and we also have duplicate delcrations of ...

```css
body .ui-prime-icons .ui-icon {
    font-family: 'primeicons', sans-serif;
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    display: inline-block;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```

In calculator.css, timepicker.css  

Thoughts?
