### ISSUE TITLE
TimePicker: CSS Updates

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#204]
We use TimePicker heavily in our apps and for new premium themes it doesn't look quite like it used to.  

I am going to update the CSS to look great by default in Omega and Nova-Light themes.  For all other premium themes you simply need to add this SCSS in your __extensions.scss_ provided by PrimeTek to have it styled for your theme.

```css
/** PrimeFaces Extensions TimePicker used heavily in ExSchedule */
.ui-timepicker {
    background-color: $panelContentBgColor;

    .ui-timepicker-table {
        background-color: $panelContentBgColor;
        color: $textColor;
    }
    .ui-timepicker-title {
        border: $inputListBorder;
        padding: 0 1em;
    }
    .ui-timepicker-table td a {
        width: 2em;
        text-align: center;

        &.ui-state-active {
            color: $primaryTextColor;
            background-color: $primaryColor;
        }

        &.ui-state-default {
            border: 1px solid $inputBorderColor;
            padding: 0.286em;
            color: $textColor;
            
            &.ui-state-active {
                color: $primaryTextColor;
                background-color: $primaryColor;
            }
        }
    }

    td.ui-timepicker-minutes {
        padding-left: 4px;
        padding-right: 4px;
        padding-bottom: 4px;
        border-left: 1px solid $inputBorderColor;
    }
}
```

If using FontAwesome instead of PrimeIcons also add this.
```css
.pe-timepicker-trigger {
    .ui-icon-clock {
        @include icon_override("\f017");
    }
}
```
