### ISSUE TITLE
InputPhone: country dropdown is clipped in p:dataTable

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#511]
<img width="504" alt="Screenshot 2021-08-20 at 11 58 36" src="https://user-images.githubusercontent.com/7500178/130216678-c720cada-63b1-486d-bd48-5761c120f0b4.png">

**Comment by jepsar** [comment]
It is caused by this CSS rule from the components CSS:

```css
.ui-datatable thead th, .ui-datatable tbody td, .ui-datatable tfoot td, .ui-datatable tfoot th {
    overflow: hidden;
}
```

For sure I cannot fix that in the `InputPhone` component, and I doubt it should be changed in the PF CSS. @sqores WDYT?

I'm closing this issue here. Can be overridden in your local project if needed.
